version: "3.4"

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./db-init-scripts:/docker-entrypoint-initdb.d
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    depends_on:
      - "database"
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      DATABASE_URL: "postgres://postgres:password@database/myapp"
      SHADOW_DATABASE_URL: "postgres://postgres:password@database/myapp_shadow"
      ROOT_DATABASE_URL: "postgres://postgres:password@database/postgres"
    ports:
      - "5000:5000"
